"""Extended binary Golay code and Leech-lattice 12-dimensional sections."""

from __future__ import annotations

import itertools

import numpy as np


def golay24_codewords() -> np.ndarray:
    """4096 codewords of G24 as a (4096, 24) uint8 array.

    G23 is the cyclic code generated by
        g(x) = 1 + x^2 + x^4 + x^5 + x^6 + x^10 + x^11
    (Wikipedia: Extended binary Golay code). G24 is G23 plus even parity.
    """
    g = np.zeros(23, dtype=np.uint8)
    for i in (0, 2, 4, 5, 6, 10, 11):
        g[i] = 1
    words23 = []
    for bits in range(1 << 12):
        p = [(bits >> i) & 1 for i in range(12)]
        acc = np.zeros(23, dtype=np.uint8)
        for i, c in enumerate(p):
            if not c:
                continue
            for j in range(12):
                if g[j]:
                    acc[(i + j) % 23] ^= 1
        words23.append(acc)
    W = np.stack(words23)
    # even-parity extension
    parity = W.sum(axis=1) % 2
    ext = np.concatenate([W, parity[:, None]], axis=1)
    return ext.astype(np.uint8)


def golay_stats(C: np.ndarray) -> dict:
    wt = C.sum(axis=1)
    from collections import Counter

    return {
        "n": int(C.shape[0]),
        "weights": dict(sorted(Counter(wt.tolist()).items())),
        "min_nonzero": int(wt[wt > 0].min()) if np.any(wt > 0) else None,
    }


def leech_minima_integer() -> tuple[np.ndarray, np.ndarray]:
    """Return two families of Leech minima as integer 24-vectors of norm^2 32.

    Type A: ±2 on a Golay octad, even number of minus signs.
    Type B: (±3, ±1^23) with sign pattern a Golay codeword (see Conway–Sloane).
    """
    C = golay24_codewords()
    wt = C.sum(axis=1)
    octads = C[wt == 8]
    # Type A
    type_a = []
    for oc in octads:
        pos = np.flatnonzero(oc)
        # even number of minuses: 2^7 patterns after fixing product of signs +1
        for bits in range(1 << 7):
            signs = np.ones(8, dtype=np.int8)
            for i in range(7):
                if (bits >> i) & 1:
                    signs[i] = -1
            if signs[:7].prod() == -1:
                signs[7] = -1
            else:
                signs[7] = 1
            v = np.zeros(24, dtype=np.int8)
            v[pos] = (2 * signs).astype(np.int8)
            type_a.append(v)
    A = np.stack(type_a) if type_a else np.zeros((0, 24), dtype=np.int8)

    # Type B: for each position j of the ±3 and each golay word c,
    # v_i = ±1, with v_j = ±3, signs from 1-2c (c in {0,1}).
    # Standard: v_i =  (-1)^{c_i}  except coordinate j where we put
    #  (-1)^{c_j} * 3, and we need sum of coords ≡ 0 mod 8 or similar.
    # Conway–Sloane: all vectors of the form
    #   ( ∓3, ±1^23 )  where the upper signs are on a Golay codeword.
    # There are 24 * 2^12 = 98304 such, matching the known count.
    type_b = []
    for j in range(24):
        for c in C:
            s = np.where(c == 0, 1, -1).astype(np.int8)
            v = s.copy()
            v[j] = np.int8(3 * s[j])
            type_b.append(v)
    B = np.stack(type_b)
    return A, B


def leech_type_4_2() -> np.ndarray:
    """1104 vectors of shape (±4)^2 0^22, squared norm 32."""
    rows = []
    for i in range(24):
        for j in range(i + 1, 24):
            for si in (4, -4):
                for sj in (4, -4):
                    v = np.zeros(24, dtype=np.int8)
                    v[i] = si
                    v[j] = sj
                    rows.append(v)
    A = np.stack(rows)
    assert A.shape[0] == 1104
    return A


def all_leech_minima() -> np.ndarray:
    A, B = leech_minima_integer()
    C = leech_type_4_2()
    M = np.concatenate([A, B, C], axis=0)
    return M


def coordinate_12_section(A: np.ndarray, B: np.ndarray, coords: slice | list[int]) -> np.ndarray:
    """Leech minima supported on a 12-set, as unit vectors in R^12."""
    idx = list(range(12) if isinstance(coords, slice) else coords)
    rest = [i for i in range(24) if i not in idx]
    vecs = []
    for fam in (A, B):
        if len(fam) == 0:
            continue
        mask = np.all(fam[:, rest] == 0, axis=1)
        sub = fam[mask][:, idx]
        for v in sub:
            n = np.dot(v, v)
            if n == 0:
                continue
            vecs.append(v.astype(np.float64) / np.sqrt(n))
    if not vecs:
        return np.zeros((0, 12))
    X = np.stack(vecs)
    # unique up to float
    # drop duplicates
    key = np.round(X, 8)
    _, uidx = np.unique(key, axis=0, return_index=True)
    return X[np.sort(uidx)]


def diagonal_section(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """Vectors of the form (x, x) in Leech, mapped to x/||x|| in R^12."""
    vecs = []
    for fam in (A, B):
        for v in fam:
            if np.array_equal(v[:12], v[12:]):
                x = v[:12].astype(np.float64)
                n = np.dot(x, x)
                if n > 0:
                    vecs.append(x / np.sqrt(n))
    if not vecs:
        return np.zeros((0, 12))
    X = np.stack(vecs)
    key = np.round(X, 8)
    _, uidx = np.unique(key, axis=0, return_index=True)
    return X[np.sort(uidx)]
